background=\EFI\visor\backgrounds\visor-wallpaper.png

title_color={{ colors.primary.default.hex }}
name_color={{ colors.on_surface.default.hex }}
highlight_color={{ colors.on_surface.default.hex }}
info_color={{ colors.on_surface_variant.default.hex }}
bg_color={{ colors.surface_variant.default.hex }}

blur=1
blur_color={{ colors.on_secundary.default.hex }}

underline_color={{ colors.on_primary.default.hex }}

shutdown_color={{ colors.on_error.default.hex }}
reboot_color={{ colors.on_surface.default.hex }}
firmware_color={{ colors.error.default.hex }}

