timeout=-1
default=0
selfheal=0
quiet=1
editor=0

resolution=1920x1080
title=none
show_names=0
center_info=0
box_radius=0
mouse=1
#mouse_speed=4
font=jetbrains
logo=none
logo_mode=none
theme=noctalia
anim_speed=10

icon_size=100
underline_thickness=3

power_icons=1
power_icon_size=44
shutdown_icon=\EFI\visor\icons\power_shutdown.png
reboot_icon=\EFI\visor\icons\power_reboot.png
firmware_icon=\EFI\visor\icons\power_bios.png

screensaver_delay=3000
screensaver_blank=3300

entry {
    name = "Arch"
    icon = \EFI\visor\icons\arch.png
    kernel = \EFI\Linux\arch-linux.efi
}

entry {
    name   = "Windows"
    icon   = \EFI\visor\icons\windows.png
    kernel = \EFI\Microsoft\Boot\bootmgfw.efi
}

